notify = true
gapless = true
volnorm = false
audio_cache = true
use_nerdfont = true
initial_screen = "cover"
playback_state= "Paused"
default_keybindings = true
statusbar_format = "%title (%artists)"

[track_format]
center = "%album"
right = "%duration"
left = "%title (%artists)"

[theme]
error = "black"
title = "#cba6f7"
primary = "#cdd6f4"
playing = "#cba6f7"
cmdline = "#cdd6f4"
secondary = "bac2de"
error_bg = "#f38ba8"
statusbar = "#191414"
highlight = "#000000"
background = "default"
playing_bg = "default"
cmdline_bg = "#191414"
search_match = "#f38ba8"
statusbar_bg = "#cba6f7"
highlight_bg = "#a6e3a1"
playing_selected = "#000000"
statusbar_progress = "#cba6f7"
