alias l="exa"
alias vi="nvim"
alias vim="nvim"
alias cz="chezmoi"
alias hdd="cd $HDD"
alias ll="exa -lh --icons --sort=type"
alias ssh="TERM=xterm-256color $(which ssh)"
alias cp="rsync --progress --recursive --archive"
alias ls="exa -lh --icons --sort=type --git-ignore"
alias lt="exa -lhT --icons --sort=type --git-ignore"
alias la="exa -lha --icons --sort=type --git-ignore"
