alias l="exa"
alias vi="nvim"
alias vim="nvim"
alias cz="chezmoi"
alias hdd="cd $HDD"
alias ll="exa -l@h --icons --sort=type"
alias cp="rsync --progress --recursive --archive"
alias ls="exa -l@h --icons --sort=type --git-ignore"
alias lt="exa -l@hT --icons --sort=type --git-ignore"
alias la="exa -l@ha --icons --sort=type --git-ignore"
