ipc_socket = true
live_config_reload = true
working_directory = "/home/upanda/codes"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
thickness = 0.15
vi_mode_style = "Beam"
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Off"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 11.0
builtin_box_drawing = true

[font.normal]
style = "Regular"
family = "JetBrainsMono Nerd Font"
