vim.keymap.set("n", "<C-a>", "ggVG", { noremap = true, silent = true })
vim.keymap.set("v", "<A-Up>", ":m '<-2<cr>gv=gv", { noremap = true, silent = true })
vim.keymap.set("n", "<A-Up>", "<cmd>m .-2<cr>==", { noremap = true, silent = true })
vim.keymap.set("v", "<A-Down>", ":m '>+1<cr>gv=gv", { noremap = true, silent = true })
vim.keymap.set("n", "<A-Down>", "<cmd>m .+1<cr>==", { noremap = true, silent = true })
vim.keymap.set("i", "<A-Up>", "<esc><cmd>m .-2<cr>==gi", { noremap = true, silent = true })
vim.keymap.set("i", "<A-Down>", "<esc><cmd>m .+1<cr>==gi", { noremap = true, silent = true })
